build: Test against Go 1.20
decred/dcrtime pull request #91
Opened 2023-06-14 00:08 UTC by dajohi

2023-06-14 08:19 UTC, jholdstock commented on .golangci.yml
> +output:
I suggest removing this, [rationale here](https://github.com/decred/dcrvotingweb/pull/290#discussion_r1229206494)

2023-06-17 00:24 UTC, davecgh requested changes

2023-06-17 00:24 UTC, davecgh commented on go.mod
> +	decred.org/dcrwallet/v2 v2.2.0
This is v3 now.

2023-06-17 00:24 UTC, davecgh commented on .github/workflows/go.yml
> +        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 #v3.5.0
Latest is `fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.01` .

2023-06-17 00:24 UTC, davecgh commented on .github/workflows/go.yml
> +        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
Latest is ` c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3` .

2023-06-17 00:24 UTC, davecgh commented on .github/workflows/go.yml
> +        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.2"
Latest is `v1.53.3`.

2023-06-17 00:24 UTC, davecgh commented on dcrtimed/backend/filesystem/filesystem_test.go
> +		t.Fatalf("want %#v got %#v", fr, *fr2)
Seems like this won't produce as useful output.

2023-06-17 00:24 UTC, davecgh commented on dcrtimed/backend/filesystem/fsck.go
> +		return fmt.Errorf("   *** ERROR empties not pruned: %#v ",
Similarly, this won't produce as nice of output.

2023-07-06 16:14 UTC, davecgh approved these changes

2023-07-06 17:26 UTC, merged